<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>CMS21-Together-Hotfix</AssemblyName>
    <RootNamespace>CMS21TogetherHotfix</RootNamespace>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Main.cs" />
    <Compile Include="Patches.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MelonLoader"><HintPath>Libs\MelonLoader.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>Libs\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnhollowerBaseLib"><HintPath>Libs\UnhollowerBaseLib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>Libs\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>Libs\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="CMS21-Together"><HintPath>Libs\CMS21-Together.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
